instagram_web/blueprints/users/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from models.user import User
from models.image import Image
from flask_login import current_user,login_required, login_user
from instagram_web.util.helpers import upload_file_to_s3
from werkzeug.utils import secure_filename
import datetime
import os



users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route('/sign_up', methods=['GET'])
def sign_up():
    return render_template('users/sign_up.html')


@users_blueprint.route('/', methods=['POST'])
def create():
    username = request.form.get('username')
    email = request.form.get('email')
    password = request.form.get('password')
    cfm_password = request.form.get('cfm_password')

    if password == cfm_password:
        user = User(username=username, email=email, password=password, cfm_password=cfm_password)
        if user.save():
            flash('Successfully registered', 'alert alert-success')
            # return redirect(url_for('home'))
            login_user(user)
            return redirect(url_for('users.show',username=username))
        else:
            for error in user.errors:
                flash(error,'alert alert-danger')
            return render_template('users/sign_up.html')
    else:
        flash('Password confirmation does not match!','alert alert-danger')
        return render_template('users/sign_up.html')


@users_blueprint.route('/<username>', methods=["GET"])
def show(username):

    if current_user.is_authenticated:
        user = User.get_or_none(User.username == username)
        images = Image.select().where(Image.user==user.id)
        if user:
            return render_template('users/show.html',user=user,images=images)
        else:
            return render_template('404.html')  
    else:
        flash('Login required.','alert alert-danger')
        return render_template('sessions/login.html')

@users_blueprint.route('/', methods=["GET"])
def index():
    return "USERS"


@users_blueprint.route('/<id>/edit', methods=['GET'])
@login_required
def edit(id):
    user = User.get_by_id(id)
    if current_user == user:
        return render_template('users/edit.html')
    else:
        flash('Unauthorized to edit','alert alert-danger')
        return redirect(url_for('users.show',username=current_user.username))


@users_blueprint.route('/<id>', methods=['POST'])
def update(id):
    user = User.get_by_id(id)
    if current_user == user:
        email = request.form.get('email')
        password = request.form.get('password')
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')

        if email != '':
            user.email = email
            user.password = None
        if first_name != '':
            user.first_name = first_name
            user.password = None
        if last_name != '':
            user.last_name = last_name
            user.password = None
        if password != '':
            user.password = password
        if user.save():
            flash('Profile updated successfully!','alert alert-success')
            return redirect(url_for('users.show',username=current_user.username))
        else:
            for error in user.errors:
                flash(error,'alert alert-danger')
            return redirect(url_for('home'))
    else: 
        flash('Unauthorized to edit','alert alert-danger')
        return redirect(url_for('users.show',username=current_user.username))



# function to check file extension
def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1].lower() in os.getenv('ALLOWED_EXTENSIONS')

@users_blueprint.route('/upload', methods=['POST'])
def upload():

    # check whether an input field with name 'user_file' exist
    if 'user_file' not in request.files:
        flash('No user_file key in request.files','alert alert-danger')
        return redirect(url_for('users.edit',id=current_user.id))

    # after confirm 'user_file' exist, get the file from input
    file = request.files['user_file']

    # check whether a file is selected
    if file.filename == '':
        flash('No selected file','alert alert-danger')
        return redirect(url_for('users.edit',id=current_user.id))

    # check whether the file extension is allowed (eg. png,jpeg,jpg,gif)
    if file and allowed_file(file.filename):
        file.filename = secure_filename(f"{str(datetime.datetime.now())}{file.filename}")
        output = upload_file_to_s3(file) 
        if output == file.filename:
            User.update(profile_image=output).where(User.id==current_user.id).execute()
            flash("Profile image successfully changed!","alert alert-success")
            return redirect(url_for('users.edit',id=current_user.id))
        else:
            flash("Image upload failed","alert alert-danger")
            return redirect(url_for('users.edit',id=current_user.id))

    # if file extension not allowed
    else:
        flash("File type not accepted,please try again.",'alert alert-danger')
        return redirect(url_for('users.edit',id=current_user.id))

instagram_web/blueprints/users/templates/users/edit.html
{% extends '_layout.html' %}

{% block content %}
<div class="container">
    <h1>Update profile</h1>
    <form action={{ url_for('users.update',id=current_user.id) }} method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" name="email" class="form-control">
            <label for="password">password</label>
            <input type="password" name="password" class="form-control">
            <br>
            <h2>Personal information</h2>
            <label for="first_name"">First name</label>
            <input type=" text" name="first_name" class="form-control">
            <label for="last_name"">Last name</label>
            <input type=" text" name="last_name" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
    
    <form action="{{ url_for('users.upload') }}" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <br>
        <h2>Upload profile image</h2>
        <div class="input-group">
            <div class="custom-file">
                <input type="file" id="customFile" class="custom-file-input" name="user_file" id="inputGroupFile04"
                    aria-describedby="inputGroupFileAddon04">
                <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
            </div>
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit" id="inputGroupFileAddon04">Upload</button>
            </div>
        </div>
    </form>

    <form action="{{ url_for('images.upload') }}" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <br>
        <h2>Upload user images</h2>
        <div class="input-group">
            <div class="custom-file">
                <input type="file" id="customFile" class="custom-file-input" name="user_file" id="inputGroupFile04"
                    aria-describedby="inputGroupFileAddon04">
                <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
            </div>
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit" id="inputGroupFileAddon04">Upload</button>
            </div>
        </div>
    </form>


    <!-- code beyond this point is all from jinqwen's. -->
<!-- 
    <form action="{#{{ url_for('users.upload') }}#}" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <div class="px-0">
            <label for="password">Profile image :</label>
            <div class="input-group">
                <div class="custom-file">
                    <input type="file" id="customFile" class="custom-file-input" name="user_file" id="inputGroupFile04"
                        aria-describedby="inputGroupFileAddon04">
                    <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
                </div>
                <div class="input-group-append">
                    <button class="btn btn-outline-success" type="submit" id="inputGroupFileAddon04">Upload</button>
                </div>
            </div>
        </div>
        <div class="text-center rounded mt-4">
            <img id="image" width="400" />
        </div>
    </form>
</div>
<script>
    let editButtons = document.getElementsByClassName('edit')
    for (let i = 0; i < editButtons.length; i++) {
        editButtons[i].addEventListener('click', function (e) {
            if (e.target.previousElementSibling.hasAttribute('disabled')) {
                e.target.previousElementSibling.removeAttribute('disabled')
            }
            else {
                e.target.previousElementSibling.setAttribute('disabled', true)
            }
        })
    }
    // live preview image
    document.getElementById("customFile").onchange = function () {
        let reader = new FileReader();
        reader.onload = function (e) {
            document.getElementById("image").src = e.target.result;
        };
        reader.readAsDataURL(this.files[0]);
    };
    $('.custom-file-input').on('change', function () {
        let fileName = $(this).val().split('\\').pop();
        $(this).next('.custom-file-label').addClass("selected").html(fileName);
    });
</script> -->

{% endblock %}

instagram_web/blueprints/users/templates/users/show.html
{% extends '_layout.html' %}

{% block content %}
<div class="container">
    <div class="row my-5">
        <div class="col-md-6" style="display: flex; 
        justify-content: center;">
            <div style="background-image: url('{{ user.profile_image_url }}');
            width: 200px;
            height: 200px;
            background-size: cover;
            background-position: center;
            border:2px solid black;
            border-radius: 50%">
            </div>
        </div>

        <div class="col-md-6">
            <div>
                <div class="d-flex">
                    <h3>{{ user.username }}</h3>
                    <div class="px-3">
                        {% if current_user != user %}
                            {% if current_user.follow_status(user) %}
                                {% if current_user.follow_status(user).approved %}
                                    <a class="btn btn-outline-dark btn-sm" href="#" data-toggle="modal"
                                        data-target="#unfollow">Following</a>
                                {% else %}
                                    <a class="btn btn-outline-dark btn-sm" href="#" data-toggle="modal"
                                        data-target="#pending">Requested</a>
                                {% endif %}
                            {% else %}
                                <a class="btn btn-outline-dark btn-sm"
                                    href="{{ url_for('follows.create',idol_id=user.id) }}">Follow</a>
                            {% endif %}
                        {% else %}
                            <a class="btn btn-outline-secondary btn-sm" href="{{ url_for('users.edit',id=current_user.id) }}">Edit</a>
                        {% endif %}
                    </div>
                </div>
                <h5>{{ user.email }}</h5>
            </div>

            <div class="mr-5 my-5">
                <div class="container" style="display: flex; justify-content: space-between;">
                    <div class="text-center">
                        <p>Posts</p>
                        <p>{{ user.images | length }}</p>
                    </div>
                    <div class="text-center">
                        <p>Followings</p>
                        <p>{{ user.followings | length }}</p>
                    </div>
                    <div class="text-center">
                        <p>Followers</p>
                        <p>{{ user.followers | length }}</p>
                    </div>
                    <div class="text-center">
                        <p>Likes</p>
                        <p>0</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="container mt-5">
        {% if current_user==user or user.private==False or current_user.follow_status(user).approved %}
        <div class="row mt-3">
            {% for image in images %}
            <div class="col-md-4 mb-5">
                <div class="card">
                    <div class="card-image">
                        <div style="background-image: url('{{ image.image_url }}');
                    background-size: cover; 
                    background-repeat: no-repeat;
                    padding-top: 90%;
                    background-position: center;">
                        </div>
                    </div>
                    {% if current_user != user %}
                    <a href="{{ url_for('donations.new',id=image.id) }}" class="btn btn-primary">Donate</a>
                    <p class="text-center">Donations: ${{ image.donations | sum(attribute='amount')}}</p>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <h5 class="text-center text-secondary mt-5">This profile is Private, <br/> follow @{{ user.username }} to view profile.</h5>
        {% endif %}
    </div>

    <div class="modal fade" id="pending" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-body text-center">
              <img src="{{user.profile_image_url }}" width="100" class="rounded-circle my-3" alt="profile_image" />
              <p>Are you sure you want to unfollow <strong>@{{user.username}}</strong>, you'll have to request to follow again if you wish to see.</p>
              <a href="{{url_for('follows.unfollow',idol_id=user.id)}}" class="btn btn-primary">Unfollow</a>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="unfollow" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-body text-center">
              <img src="{{user.profile_image_url }}" width="100" class="rounded-circle my-3" alt="profile_image" />
              <p>Unfollow <strong>@{{user.username}}</strong>?</p>
              <a href="{{url_for('follows.unfollow',idol_id=user.id)}}" class="btn btn-primary">Unfollow</a>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
</div>


{% endblock %}

instagram_web/blueprints/users/templates/users/sign_up.html
{% extends '_layout.html' %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form action={{ url_for('users.create') }} method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <label for="username">Username :</label>
            <input type="text" name="username" class="form-control" />
            <label for="email">Email :</label>
            <input type="email" name="email" class="form-control" />
            <label for="password">Password :</label>
            <input type="password" name="password" class="form-control" />
            <label for="cfm_password">Confirm Password :</label>
            <input type="password" name="cfm_password" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
</div>
{% endblock %}