instagram_web/blueprints/follows/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.user import User
from models.follows import Follows
from flask_login import current_user, login_required
import os

follows_blueprint = Blueprint('follows',
                            __name__,
                            template_folder='templates')

@follows_blueprint.route('/<idol_id>')
@login_required
def create(idol_id):
    idol = User.get_by_id(idol_id)
    if current_user.follow(idol):
        if idol.private:
            flash(f'You\'ve sent a follow request to {idol.username}.','alert alert-success')
        else:
            flash(f'You are now following {idol.username}.','alert alert-success')
        return redirect(url_for('users.show', username=idol.username))
    else:
        flash(f"You can't view {idol.username}'s profile yet.","alert alert-danger")
        return render_template('users/show.html',username=idol.username)

@follows_blueprint.route('/<fan_id>/delete')
@login_required
def destroy(fan_id):
    fan = User.get_by_id(fan_id)
    if fan.unfollow(current_user):
        flash(f'You have rejected the request from {fan.username}.','alert alert-success')
        return redirect(url_for('users.show',username=current_user.username))
    else:
        flash('Something went wrong, try again later.','alert alert-danger')
        return render_template('users/show.html',username=current_user.username)

@follows_blueprint.route('/<idol_id>/unfollow')
@login_required
def unfollow(idol_id):
    idol = User.get_by_id(idol_id)
    if current_user.unfollow(idol):
        flash(f"You have unfollowed {idol.username}.","alert alert-success")
        return redirect(url_for('users.show', username=idol.username))
    else:
        flash(f"Unfollow {idol.username} unsuccesful","alert alert-danger")
        return render_template('users/show.html',username=idol.username)
    
@follows_blueprint.route('/<fan_id>/update')
@login_required
def update(fan_id):
    fan = User.get_by_id(fan_id)
    if current_user.approve_request(fan):
        flash(f'You\'ve approved the follow request from {fan.username}','alert alert-success')
        return redirect(url_for('users.show', username=current_user.username))
    else:
        flash(f'Something went wrong, try again later.','alert alert-danger')
        return render_template('users/show.html', username=current_user.username)

instagram_web/blueprints/users/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from models.user import User
from models.image import Image
from flask_login import current_user,login_required, login_user
from instagram_web.util.helpers import upload_file_to_s3
from werkzeug.utils import secure_filename
import datetime
import os



users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route('/sign_up', methods=['GET'])
def sign_up():
    return render_template('users/sign_up.html')


@users_blueprint.route('/', methods=['POST'])
def create():
    username = request.form.get('username')
    email = request.form.get('email')
    password = request.form.get('password')
    cfm_password = request.form.get('cfm_password')

    if password == cfm_password:
        user = User(username=username, email=email, password=password, cfm_password=cfm_password)
        if user.save():
            flash('Successfully registered', 'alert alert-success')
            # return redirect(url_for('home'))
            login_user(user)
            return redirect(url_for('users.show',username=username))
        else:
            for error in user.errors:
                flash(error,'alert alert-danger')
            return render_template('users/sign_up.html')
    else:
        flash('Password confirmation does not match!','alert alert-danger')
        return render_template('users/sign_up.html')


@users_blueprint.route('/<username>', methods=["GET"])
def show(username):

    if current_user.is_authenticated:
        user = User.get_or_none(User.username == username)
        images = Image.select().where(Image.user==user.id)
        if user:
            return render_template('users/show.html',user=user,images=images)
        else:
            return render_template('404.html')  
    else:
        flash('Login required.','alert alert-danger')
        return render_template('sessions/login.html')

@users_blueprint.route('/', methods=["GET"])
def index():
    return "USERS"


@users_blueprint.route('/<id>/edit', methods=['GET'])
@login_required
def edit(id):
    user = User.get_by_id(id)
    if current_user == user:
        return render_template('users/edit.html')
    else:
        flash('Unauthorized to edit','alert alert-danger')
        return redirect(url_for('users.show',username=current_user.username))


@users_blueprint.route('/<id>', methods=['POST'])
def update(id):
    user = User.get_by_id(id)
    if current_user == user:
        email = request.form.get('email')
        password = request.form.get('password')
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')

        if email != '':
            user.email = email
            user.password = None
        if first_name != '':
            user.first_name = first_name
            user.password = None
        if last_name != '':
            user.last_name = last_name
            user.password = None
        if password != '':
            user.password = password
        if user.save():
            flash('Profile updated successfully!','alert alert-success')
            return redirect(url_for('users.show',username=current_user.username))
        else:
            for error in user.errors:
                flash(error,'alert alert-danger')
            return redirect(url_for('home'))
    else: 
        flash('Unauthorized to edit','alert alert-danger')
        return redirect(url_for('users.show',username=current_user.username))



# function to check file extension
def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1].lower() in os.getenv('ALLOWED_EXTENSIONS')

@users_blueprint.route('/upload', methods=['POST'])
def upload():

    # check whether an input field with name 'user_file' exist
    if 'user_file' not in request.files:
        flash('No user_file key in request.files','alert alert-danger')
        return redirect(url_for('users.edit',id=current_user.id))

    # after confirm 'user_file' exist, get the file from input
    file = request.files['user_file']

    # check whether a file is selected
    if file.filename == '':
        flash('No selected file','alert alert-danger')
        return redirect(url_for('users.edit',id=current_user.id))

    # check whether the file extension is allowed (eg. png,jpeg,jpg,gif)
    if file and allowed_file(file.filename):
        file.filename = secure_filename(f"{str(datetime.datetime.now())}{file.filename}")
        output = upload_file_to_s3(file) 
        if output == file.filename:
            User.update(profile_image=output).where(User.id==current_user.id).execute()
            flash("Profile image successfully changed!","alert alert-success")
            return redirect(url_for('users.edit',id=current_user.id))
        else:
            flash("Image upload failed","alert alert-danger")
            return redirect(url_for('users.edit',id=current_user.id))

    # if file extension not allowed
    else:
        flash("File type not accepted,please try again.",'alert alert-danger')
        return redirect(url_for('users.edit',id=current_user.id))

instagram_web/templates/_layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="shortcut icon" href="{{ url_for('static', filename='image/favicon.ico') }}">

    {% assets "home_css" %}
      <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

    {% assets "home_js" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

    {% block header %}
    {% endblock %}

    <title>
      {% block title %}
      {% endblock %}NEXTAGRAM
    </title>

  </head>
  <body>
    {% include '_navbar.html' %}
    {% with messages = get_flashed_messages(with_categories = true) %}
      {% if messages %}
        <ul style="padding-inline-start:0" class="flashes">
          {% for category,message in messages %}
          <li style="list-style:none; text-align:center; margin-bottom:0px; border:none" 
          class="{{ category }}">{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    {% block content %}
    {% endblock %}
    <footer>
      Made with &hearts; at <a target="_blank" href="https://www.nextacademy.com/?utm_source=github&utm_medium=student-challenge&utm_campaign=flask-nextagram">NEXT Academy</a>
    </footer>
  </body>
</html>

instagram_web/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('home') }}">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline my-2 my-lg-0 ml-auto">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% if current_user.is_authenticated %}
        <ul class="navbar-nav mx-2">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    {{ current_user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ url_for('users.show',username = current_user.username) }}">View profile</a>
                    <a class="dropdown-item" href="{{ url_for('users.edit',id=current_user.id) }}">Edit profile</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">{{ current_user.get_request|length }} Requests
                </a>
                <div class="dropdown-menu">
                    <h6 class="dropdown-item disabled text-center" aria-labelledby="navbarDropdown">
                        {{ current_user.get_request|length }} requests</h6>
                    {% for request in current_user.get_request %}
                    <div class="dropdown-item">
                        <a href="{{ url_for('users.show',username=request.fan.username) }}">
                            <img src="{{ request.fan.profile_image_url }}" width="50"
                                class="img-thumbnail rounded-circle">
                            <span class="px-2">{{ request.fan.username }}</span>
                        </a>
                        <div class="py-3">
                            <a class="btn btn-primary btn-sm"
                                href="{{ url_for('follows.update',fan_id=request.fan.id) }}">Confirm</a>
                            <a class="btn btn-dark btn-sm"
                                href="{{ url_for('follows.destroy',fan_id=request.fan.id) }}">Delete</a>
                        </div>
                        <div class="dropdown-divider"></div>
                    </div>
                    {% endfor %}
                </div>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('sessions.logout') }}">Log Out</a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav mx-2">
            <li class="nav-item">
                <a class="nav-link" href={{ url_for('sessions.login') }}>Log In</a>
            </li>
            <li class="nav-item mx-2">
                <a class="nav-link" href={{ url_for('users.sign_up') }}>Sign Up</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>

instagram_web/templates/home.html
{% extends "_layout.html" %}

{% block title %}
Homepage
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<div class="container">
  <h1>Homepage</h1>
</div>
{% endblock %}